### PR TITLE
collect httpd logs with promtail

### PR DESCRIPTION
**Pull request by butlerx**

### CODE REVIEW

**Review by m1cr0man — COMMENTED** [review]
Afaik we do have the option of changing the httpd log format to something more easily parsed in the first place. I feel this would make more sense, we should be looking at logs in Grafana more often than we do in plain text, otherwise we're doing something wrong.

**Comment by butlerx** [comment]
im unsure what you're suggesting to change about the pr

**Comment by m1cr0man** [comment]
I'm saying we could change the httpd log format to something more easily parseable. http://httpd.apache.org/docs/current/mod/mod_log_config.html#logformat What do you think?

**Comment by butlerx** [comment]
ah, then we should look at just outputting key-value or JSON logs directly and avoid needing to write parsing rules at all.
Personally I'm happier if we update the logs to output key value.

If we are modifying the logs to be more easily parsable we could use rsyslog to read the files 
```
input(type="imfile"
	File="/var/log/httpd/access-*.log"
	Tag="apache/access.log"
	Ruleset="sendToLogserver")```

**Comment by butlerx** [comment]
something like 
```
LogFormat "{ \"time\":\"%t\", \"remoteIP\":\"%a\", \"host\":\"%V\", \"request\":\"%U\", \"query\":\"%q\", \"method\":\"%m\", \"status\":\"%>s\", \"userAgent\":\"%{User-agent}i\", \"referer\":\"%{Referer}i\" }" accessJson
```

**Comment by m1cr0man** [comment]
That sounds good! We already have rsyslogd configured on all hosts.

**Comment by butlerx** [comment]
looking at how docker implemented logs to stdout 
```	
sed -ri \
		-e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' \
		-e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' \
		-e 's!^(\s*TransferLog)\s+\S+!\1 /proc/self/fd/1!g' \
```
but httpd is having issues accessing these

**Comment by m1cr0man** [comment]
What was left to do here? Wouldn't mind having some httpd data :)

**Comment by butlerx** [comment]
Looking at the last change was logging to journald rather than syslog or file. 
So I think just testing left

**Comment by butlerx** [comment]
tested on rbtest and verified working

**Review by m1cr0man — APPROVED** [review]
Cool. Will this deprecate/remove the on-disk http logs? I would be inclined to do that given we have over 4000 file handles for vhost log files.

**Comment by butlerx** [comment]
Yep no log files anymore

**Pull request merged**
