### PR TITLE
channel map

### PR DESCRIPTION
**Pull request by butlerx**
- Remerge irc discord channels

merge after #86

### CODE REVIEW

**Comment by m1cr0man** [comment]
~Is this not a draft anymore?~ Nevermind, lets get #86 in

**Review by cmgn — APPROVED** [review]
I double checked all the IDs; looks good.

What happens if somebody on IRC sends a message to #rbAnouncements? are the permissions set up in a way that stops the "bot" from posting on the matching Discord channel? at the moment we have it set up so that only committee members can post to it.

**Comment by butlerx** [comment]
Currently the channel is set to mute so no one can talk. I'll take the bridge down register the channel and register it with chanserv and set it to mute and give the bridge permission to talk. Should mean only cmt(or an irc oper) can talk from discord

**Comment by butlerx** [comment]
Deployed, we should be able to clean up the old channels

**Pull request merged**
